version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.11"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    user: vscode
    env_file: .env
    depends_on:
      - db
  db:
    image: phidata/pgvector:16
    restart: unless-stopped
    container_name: pgvector
    env_file: postgres.env
    expose:
      - "5532" 
    command: -p 5532
volumes:
  postgres-data: